import './globals.css';
import { Inter } from 'next/font/google';
import { LoginContextProvider } from '@/context/LoginContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginContextProvider>{children}</LoginContextProvider>
      </body>
    </html>
  );
}
